# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170913_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='about',
        ),
    ]
