# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170927_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='É da equipe?'),
        ),
    ]
