# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='comfirmed',
            new_name='confirmed',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
